/**
 * Generates the Observatory's data file from the real golden-case scenarios in
 * `core/__golden__/scenarios.ts` — the exact same code the two golden-case tests run and assert
 * against. Run this after any change to the scenarios or the engines they exercise:
 *
 *   bun run observatory/scripts/capture-golden-events.ts
 *
 * The Observatory is a replay of this file's output, not a live view — there is no live
 * cross-system traffic through MESH yet (Laya/Jev are NOT_CONNECTED, adapters read snapshot files).
 * Regenerating and committing this JSON keeps the visualization honest: it can only ever show what
 * a real, currently-passing test run actually produced.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { AT, buildFragileReplayScenario, buildLessonProvisionalScenario } from '../../core/__golden__/scenarios';
import { ProvisionalLessonError } from '../../core/learning-ledger';

const case1 = buildFragileReplayScenario();
const case2 = buildLessonProvisionalScenario();

let blockedMessage = '';
try {
  case2.learning.transition(case2.lesson.id, 'ADOPTED', 'attempting promotion', AT);
} catch (err) {
  if (!(err instanceof ProvisionalLessonError)) throw err;
  blockedMessage = err.message;
}

const output = {
  generated_at: new Date().toISOString(),
  source: 'core/__golden__/scenarios.ts (same code the golden-case tests assert against)',
  note: 'DEC-001 is risk-replay\'s own seeded demo/golden-dataset decision, SIMULATED throughout, not a real incident. This is a replay of a real test run, not a live feed.',
  cases: [
    {
      title: 'Golden Case 1: Fragile Under Replay',
      case_id: case1.mesh_case.id,
      summary: case1.mesh_case.summary,
      events: case1.ledger.forCase(case1.mesh_case.id),
      blocked_attempt: null,
    },
    {
      title: 'Golden Case 2: Lesson Stays PROVISIONAL Forever',
      case_id: case2.mesh_case.id,
      summary: case2.mesh_case.summary,
      events: case2.ledger.forCase(case2.mesh_case.id),
      blocked_attempt: {
        from: 'VALIDATED',
        to: 'ADOPTED',
        message: blockedMessage,
      },
    },
  ],
};

mkdirSync(new URL('../data', import.meta.url), { recursive: true });
const fileContents = `// Generated by observatory/scripts/capture-golden-events.ts — do not hand-edit.\nexport default ${JSON.stringify(output, null, 2)};\n`;
writeFileSync(new URL('../data/golden-cases.js', import.meta.url), fileContents);
console.log(`Wrote observatory/data/golden-cases.js — ${output.cases.reduce((n, c) => n + c.events.length, 0)} real ledger events across ${output.cases.length} cases.`);
