/**
 * Generates the Observatory's repo-registry data file from the real REPOSITORY_REGISTRY in
 * adapters/repo-registry/registry.ts - the same data adapters/repo-registry/registry.test.ts
 * asserts against. Run this after any change to the registry:
 *
 *   bun run observatory/scripts/capture-repo-registry.ts
 *
 * Ask MESH reads this file to state, honestly, exactly which repositories it can and cannot
 * actually answer questions about today - never a claim of a live cross-repo connection that
 * does not exist (Ask MESH directive, 2026-09-23).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { REPOSITORY_REGISTRY } from "../../adapters/repo-registry/registry";

const output = {
  generated_at: new Date().toISOString(),
  source: "adapters/repo-registry/registry.ts (the same registry registry.test.ts asserts against)",
  note: "Declares whether MESH actually reads each repository's knowledge today and how. UNAVAILABLE means no adapter exists yet or that adapter has no client of its own - never silently omitted or guessed at.",
  repositories: REPOSITORY_REGISTRY,
};

mkdirSync(new URL("../data", import.meta.url), { recursive: true });
const NL = String.fromCharCode(10);
const fileContents = "// Generated by observatory/scripts/capture-repo-registry.ts -- do not hand-edit." + NL + "export default " + JSON.stringify(output, null, 2) + ";" + NL;
writeFileSync(new URL("../data/repo-registry.js", import.meta.url), fileContents);
console.log("Wrote observatory/data/repo-registry.js -- " + output.repositories.length + " repository entries.");
